default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  # Change the usename and password to the postgres username and password that
  # you set during the installation of postgres.
  # If you're on a Mac and installed postgres via homebrew, you can simply
  # delete the following two lines.
  username: lisapaulsavoie
  password: ""

development:
  <<: *default
  database: second-pinterest_development

test:
  <<: *default
  database: second-pinterest_test

production:
  url: <%= ENV['DATABASE_URL'] %>
