# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
# hi
development:
  secret_key_base: cd6981626cb34fb16b0588887db4254ea48d74b613551165d0b90b99fc541af7e82dfabe42c1b93eec860c18bd09555518ba251645dd9b018a4aec1e7d178b78
  access_key_id: AKIAI3RWAPHONDCX6XFA
  secret_access_key: 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
  bucket: ls-pin-app
  s3_region: us-east-1

test:
  secret_key_base: 4ed402ba12c422715938368fb2faee1adffa84b34ad0d076dbd8b52126d8d12e262fb6f1f459c991a143f4e8933464dec29483433cf55c287b531a6d84446c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
