require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.

  before(:each) do
    @user = FactoryBot.build(:user)
  end
  after(:each) do
    if !@user.destroyed?
      @user.destroy
  end
end

  let(:valid_attributes) {
    {
      first_name: @user.first_name,
      last_name: @user.last_name,
      email: @user.email,
      password: @user.password
    }
  }

# Could leave any attributes out since they are all required
  let(:invalid_attributes) {
    {
      first_name: @user.first_name,
      last_name: @user.last_name
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

    # No longer showing the user index page so no longer need to test for it
#  describe "GET #index" do
#    it "returns a success response" do
#      User.create! valid_attributes
#      get :index, {}, valid_session
#      expect(response).to be_successful
#    end
#  end

  describe "GET #show" do
    it "returns a success response" do
      user = User.create! valid_attributes
      get :show, {:id => user.to_param}, valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, {}, valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      user = User.create! valid_attributes
      get :edit, {:id => user.to_param}, valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, {:user => valid_attributes}, valid_session
        }.to change(User, :count).by(1)
      end

      it "redirects to the created user" do
        post :create, {:user => valid_attributes}, valid_session
        expect(response).to redirect_to(User.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, {:user => invalid_attributes}, valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user" do
        user = User.create! valid_attributes
        put :update, {:id => user.to_param, :user => new_attributes}, valid_session
        user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user" do
        user = User.create! valid_attributes
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
        expect(response).to redirect_to(user)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        user = User.create! valid_attributes
        put :update, {:id => user.to_param, :user => invalid_attributes}, valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user" do
      user = User.create! valid_attributes
      expect {
        delete :destroy, {:id => user.to_param}, valid_session
      }.to change(User, :count).by(-1)
    end

    it "redirects to the users list" do
      user = User.create! valid_attributes
      delete :destroy, {:id => user.to_param}, valid_session
      expect(response).to redirect_to(users_url)
    end
  end

  describe "GET login" do
    it "renders the login view" do
      get :login
      expect(response).to render_template(:login)
    end
  end

  describe "POST login" do
    # Ok, I created my own user here, but am I supposed to? or am I supposed to use FactoryBot? See below for what I had before that stopped working after I added/started using FactoryBot
    it "renders the show view if params valid" do
      user = User.create! valid_attributes 
      post :authenticate, {email: @user.email, password: @user.password}
      expect(response).to redirect_to(user_path(user.id))
    end

    it "populates @user if params valid" do
      user = User.create! valid_attributes
      post :authenticate, {email: @user.email, password: @user.password}
      expect(assigns(:user)).to eq(user)
    end

    # I'm using the test above where I create a user. Everything below stopped working after I started using FactoryBot. I still had errors afte removing the before & after. Maybe there is a better way.
#    before(:all) do
#      @user = User.create(email: "coder@skillcrush.com", password: "secret")
#      @valid_user_hash = {email: @user.email, password: @user.password}
#      @invalid_user_hash = {email: "", password: ""}
#    end

#    after(:all) do
#      if !@user.destroyed?
#        @user.destroy
#      end
#    end

#    it "renders the show view if params valid" do
#      post :authenticate, @valid_user_hash
#      expect(response).to redirect_to(user_path(@user.id))
#    end

#    it "populates @user if params valid" do
#      post :authenticate, @valid_user_hash
#      expect(assigns(:user)).to eq(@user)
#    end

    it "renders the login view if params invalid" do
      post :authenticate, @invalid_user_hash
      expect(response).to render_template(:login)
    end

    it "populates the @errors variable if params invalid" do
      post :authenticate, @invalid_user_hash
      expect(assigns[:errors].present?).to be(true)
    end
  end
end
